### ISSUE TITLE
Failed to build index.scss in production

### ISSUE THREAD

**Issue by bnhr** [tr1s/tris-webpack-boilerplate#29]
I'm using the latest boilerplate, everything works fine in development mode, but when I try to build in production mode, I got this error :

`ERROR in ./src/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: The extractor has failed to extract the selectors.
    at Purgecss.extractSelectors (/mnt/d/Web Project/Heru/heru-port2/node_modules/purgecss/lib/purgecss.js:729:15)
    at Purgecss.extractFileSelector (/mnt/d/Web Project/Heru/heru-port2/node_modules/purgecss/lib/purgecss.js:662:100)
    at /mnt/d/Web Project/Heru/heru-port2/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:80:37
    at LazyResult.run (/mnt/d/Web Project/Heru/heru-port2/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/mnt/d/Web Project/Heru/heru-port2/node_modules/postcss/lib/lazy-result.js:208:26)
    at /mnt/d/Web Project/Heru/heru-port2/node_modules/postcss/lib/lazy-result.js:213:17
    at runLoaders (/mnt/d/Web Project/Heru/heru-port2/node_modules/webpack/lib/NormalModule.js:316:20)
    at /mnt/d/Web Project/Heru/heru-port2/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /mnt/d/Web Project/Heru/heru-port2/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/mnt/d/Web Project/Heru/heru-port2/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/mnt/d/Web Project/Heru/heru-port2/node_modules/postcss-loader/src/index.js:208:9)
 @ ./src/index.js 13:0-22`

everything is successfully built but this index.scss has failed

**Comment by bnhr** [comment]
Solved by remove `keyframes `and `defaultExtractor `in postcss.config.js
